[DEN-6] WAF - Gets All Custom Rule Sets implementation
EdgeCast/ec-sdk-go pull request #11
Opened 2021-07-13 16:36 UTC by ssaluja4

Integrates the following WAF API (Get All Custom Rule Sets) into GO Lang SDK

https://dev.vdms.com/cdn/api/index.html#Media_Management/Web-Security/Get-All-Custom-Rule-Sets.htm%3FTocPath%3DWeb%2520Application%2520Firewall%7C_____11

2021-07-13 20:53 UTC, stevenpaz requested changes
Just need to remove the duplicated code from Frank's branch, otherwise looks good

2021-07-13 20:53 UTC, stevenpaz commented on edgecast/waf/custom_rule.go
> +//Allows for LastModifiedDate field within customRuleSets struct to be of formatted datetime string
shortDateTime struct and UnmarshalJSON funcs should be removed, they will conflict with Frank's code

2021-07-14 16:40 UTC, ssaluja4 commented
@stevenpaz updated based on your comments. Please review. Thanks.

2021-07-14 18:10 UTC, stevenpaz commented
Looks good to me

2021-07-14 18:11 UTC, stevenpaz approved these changes

2021-07-14 18:22 UTC, merged